baseURL = "http://edwarddbaker.org"
title = "EDWARD BAKER"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # sets how many articles will appear on the page
googleAnalytics = ""
enableRobotsTXT = true

[params]
  author = "Edward Baker"
  site_logo = "'/images/icon.jpg'"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"


